name: PR Checks

on:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Find npm projects
        id: find-projects
        run: |
          PACKAGE_FILES=$(find . -name "package.json" -not -path "*/node_modules/*" -not -path "*/\.*" | sort)
          echo "$PACKAGE_FILES" | tee project_list.txt
          echo "project_list<<EOF" >> $GITHUB_OUTPUT
          cat project_list.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Check npm projects
        run: |
          PACKAGE_FILES="${{ steps.find-projects.outputs.project_list }}"
          for PACKAGE_FILE in $PACKAGE_FILES; do
            PROJECT_DIR=$(dirname "$PACKAGE_FILE")
            PROJECT_NAME=$(basename "$PROJECT_DIR")
            echo "🔍 Checking project: $PROJECT_NAME ($PROJECT_DIR)"
            cd "$GITHUB_WORKSPACE/$PROJECT_DIR"
            echo "Installing dependencies..."
            npm ci
            if grep -q "\"test\":" package.json; then
              echo "Running tests..."
              npm test -- --watchAll=false
            fi
            if grep -q "\"build\":" package.json; then
              echo "Checking build..."
              npm run build
            fi
            cd "$GITHUB_WORKSPACE"
            echo "✅ Finished checking $PROJECT_NAME"
            echo "-------------------------------------"
          done 